import Nav from '@/components/Nav'
import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <div className='h-screen bg-hero bg-cover'>
            <Nav />
            <div className='flex justify-between'>
              <div className='mt-10 ml-24 w-4/12 justify-start'>
                <p className='font-sans font-bold text-7xl'>Hi !</p>
                <p className='font-sans font-bold text-7xl'>I Might Help Your Website Ideas to be True</p>
              
                <div className='flex text-center pt-10'>
                  <p className='font-sans font-medium text-xl'>Scroll to know more</p>
                  <a href="#" className='p-1 w-9 border-2 border-black-700 rounded-full'>A</a>
                </div>
              </div>
              <div className='w-fit relative right-10 justify-end'>
                <Image
                  src='/Headshot.png'
                  width='482'
                  height='572' 
                />
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
